### ISSUE TITLE
Migrating Submodules to Main Repo

### ISSUE THREAD

**Issue by nikeokoronkwo** [pheasantframework/pheasant#27]
This issue is a disclaimer that the repositories for the Pheasant Sibling Packages (`pheasant_temp`, `pheasant_meta`, `pheasant_build` and `pheasant_assets`) will be **archived** and soon **removed**. These packages will instead be migrated to the main `pheasant` repository here. 

This is to aid in generated workflow builds and to make development easier for all packages used in the pheasant framework.

**Comment by pheasant-framework** [comment]
Submodules have been removed in main branch
Proceeding to close down the submodule repositories after other branches have been successfully updated

**Comment by nikeokoronkwo** [comment]
Complete
